In [13]:
import numpy as np

a = np.arange(30, 71, 1)
print(a)


[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


***GENRATING RANDOM NUMBERS FROM A NORMAL DISTRIBUTION***

In [24]:
from numpy import random
random.normal(loc=[4], scale=2, size=15)


array([3.25781509, 5.00689953, 5.42652907, 5.95618973, 3.74484163,
       5.24040715, 4.73587318, 6.48767172, 6.93972791, 1.59937928,
       2.26871146, 1.26068635, 3.42925033, 2.85568135, 2.48888494])

***DOT PRODUCT***

In [28]:
a = np.array([2,3])
b = np.array([3,4])

a @ b    # @ is a short form of numpy.matmul


18

***DETERMINANT***

In [31]:
a = np.array([[2,3], [4, 5]])
np.linalg.det(a)


-2.0

***CREATING 3x3x3 ARRAY***

In [52]:
shape = (3,3,3)
random_array = np.random.rand(3,3,3)
random_array

array([[[0.79439801, 0.82632727, 0.9618586 ],
        [0.25173082, 0.29102368, 0.9812042 ],
        [0.62976629, 0.88201759, 0.50559251]],

       [[0.06524435, 0.89646111, 0.70541473],
        [0.35385001, 0.06833583, 0.54578071],
        [0.68453264, 0.64820471, 0.69088978]],

       [[0.46931374, 0.78923971, 0.32156594],
        [0.21016594, 0.00548605, 0.67751366],
        [0.75382673, 0.96327113, 0.66721294]]])

***FINDING MIN and MAX VALUES***

In [55]:
random_array = np.random.rand(5, 5)
min_value = random_array.min()
max_value = random_array.max()
print (random_array)
print(min_value)
print(max_value)

[[0.46035623 0.4411107  0.71803026 0.48312207 0.48296902]
 [0.76419849 0.55327631 0.14588091 0.25302085 0.67109984]
 [0.32247199 0.34498806 0.42378772 0.84211419 0.94452997]
 [0.80932548 0.97376083 0.76675563 0.34930315 0.3751737 ]
 [0.78158505 0.48629095 0.85710387 0.05691245 0.64584387]]
0.056912450384121405
0.9737608342379971


***FINDING MEAN, STD and VARIANCE***

In [56]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Compute the mean along the second axis (axis=1)
mean_values = np.mean(array, axis=1)

std_values = np.std(array, axis=1)

var_values = np.var(array, axis=1)

print("Array:")
print(array)
print("Mean along the second axis:", mean_values)
print("Standard deviation along the second axis:", std_values)
print("Variance along the second axis:", var_values)


Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean along the second axis: [2. 5. 8.]
Standard deviation along the second axis: [0.81649658 0.81649658 0.81649658]
Variance along the second axis: [0.66666667 0.66666667 0.66666667]
